### ISSUE TITLE
SIARD-DK: Better error message when the user (accidently) tries to export db without tables?

### ISSUE THREAD

**Issue by ThomasKristensen** [keeps/db-preservation-toolkit#125]
@andreaskring , in the (very) special case, where the user accidently tries to export a database without any tables, we should perhaps consider providing a better error message than the stack trace below. (This has low priority though I would guess, but could save the user some time figuring out what is going on.)

````
INFO [12:29:10] FINISHED: Getting the database structure.
DEBUG [12:29:10] finishing database
/schema/tableIndex.xsd
ERROR [12:29:11] Error while importing/exporting
                 Error while Marshalling JAXB
                 cvc-complex-type.2.4.b: The content of element 'tables' is not complete. One of '{"http://www.sa.dk/xmlns/diark/1.0":table}' is expected.
DEBUG [12:29:11] Error while importing/exporting
                 Error while Marshalling JAXB
                 cvc-complex-type.2.4.b: The content of element 'tables' is not complete. One of '{"http://www.sa.dk/xmlns/diark/1.0":table}' is expected.
com.databasepreservation.model.exception.ModuleException: Error while Marshalling JAXB
	at com.databasepreservation.modules.siard.out.metadata.StandardSIARDMarshaller.marshal(StandardSIARDMarshaller.java:63)
	at com.databasepreservation.modules.siard.out.metadata.SIARDDKMetadataExportStrategy.writeMetadataXML(SIARDDKMetadataExportStrategy.java:55)
	at com.databasepreservation.modules.siard.out.output.SIARDExportDefault.finishDatabase(SIARDExportDefault.java:109)
	at com.databasepreservation.modules.siard.out.output.SIARDDKDatabaseExportModule.finishDatabase(SIARDDKDatabaseExportModule.java:78)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1924)
	at com.databasepreservation.Main.internal_main(Main.java:94)
	at com.databasepreservation.Main.main(Main.java:57)
Caused by: javax.xml.bind.MarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 0; columnNumber: 0; cvc-complex-type.2.4.b: The content of element 'tables' is not complete. One of '{"http://www.sa.dk/xmlns/diark/1.0":table}' is expected.]
	at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:311)
	at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:236)
	at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:95)
	at com.databasepreservation.modules.siard.out.metadata.StandardSIARDMarshaller.marshal(StandardSIARDMarshaller.java:59)
	... 6 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 0; columnNumber: 0; cvc-complex-type.2.4.b: The content of element 'tables' is not complete. One of '{"http://www.sa.dk/xmlns/diark/1.0":table}' is expected.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.error(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.reportSchemaError(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.elementLocallyValidComplexType(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.elementLocallyValidType(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.processElementContent(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.handleEndElement(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.endElement(Unknown Source)
	at org.apache.xerces.jaxp.validation.ValidatorHandlerImpl.endElement(Unknown Source)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at com.sun.xml.internal.bind.v2.runtime.output.SAXOutput.endTag(SAXOutput.java:117)
	at com.sun.xml.internal.bind.v2.runtime.output.XmlOutputAbstractImpl.endTag(XmlOutputAbstractImpl.java:109)
	at com.sun.xml.internal.bind.v2.runtime.output.ForkXmlOutput.endTag(ForkXmlOutput.java:76)
	at com.sun.xml.internal.bind.v2.runtime.output.NamespaceContextImpl$Element.endElement(NamespaceContextImpl.java:489)
	at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.endElement(XMLSerializer.java:300)
	at com.sun.xml.internal.bind.v2.runtime.property.SingleElementNodeProperty.serializeBody(SingleElementNodeProperty.java:145)
	at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.serializeBody(ClassBeanInfoImpl.java:345)
	at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.childAsSoleContent(XMLSerializer.java:578)
	at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.serializeRoot(ClassBeanInfoImpl.java:326)
	at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.childAsRoot(XMLSerializer.java:479)
	at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:308)
	... 9 more
DEBUG [12:29:11] #########################################################
````

**Comment by chalkos** [comment]
I think this also applies to SIARD 1 and 2.
