### ISSUE TITLE
SIARD-DK: Need to decide if we want to support "xs:hexBinary" for small binary values.

### ISSUE THREAD

**Issue by ThomasKristensen** [keeps/db-preservation-toolkit#127]
@andreaskring , I guess we need to determine if we want to support / utilize xml datatype "xs:hexBinary" for small binary values, that we don't extract and store as files. Currently we seem make the initial steps to offer support:

https://github.com/magenta-aps/db-preservation-toolkit/blob/master/dbptk-core/src/main/java/com/databasepreservation/modules/siard/out/content/SIARDDKsql99ToXsdType.java#L18

...however as we don't make a registration in the LOB tracker for these binary data types:

https://github.com/magenta-aps/db-preservation-toolkit/blob/dev/dbptk-core/src/main/java/com/databasepreservation/modules/siard/out/content/SIARDDKContentExportStrategy.java#L181

...this means that we'll end up with a class cast exception, when the absence of a registation in the LOB tracker for the column, means that we assume that it is of type SimpleCell (when in fact it is of type BinaryCell).

````
  main] ERROR 2016-02-12 15:30:40,871 (Main) Unexpected exception
                 com.databasepreservation.model.data.BinaryCell cannot be cast to com.databasepreservation.model.data.SimpleCell
[main] DEBUG 2016-02-12 15:30:40,871 (Main) Unexpected exception
                 com.databasepreservation.model.data.BinaryCell cannot be cast to com.databasepreservation.model.data.SimpleCell
java.lang.ClassCastException: com.databasepreservation.model.data.BinaryCell cannot be cast to com.databasepreservation.model.data.SimpleCell
	at com.databasepreservation.modules.siard.out.content.SIARDDKContentExportStrategy.tableRow(SIARDDKContentExportStrategy.java:277)
	at com.databasepreservation.modules.siard.out.output.SIARDExportDefault.handleDataRow(SIARDExportDefault.java:104)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1910)
	at com.databasepreservation.Main.internal_main(Main.java:94)
	at com.databasepreservation.Main.internal_main(Main.java:63)
	at com.databasepreservation.testing.integration.roundtrip.Roundtrip.roundtrip(Roundtrip.java:159)
	at com.databasepreservation.testing.integration.roundtrip.Roundtrip.testTypeAndValue(Roundtrip.java:102)
	at com.databasepreservation.testing.integration.roundtrip.MySqlSIARDDKTest.testQueries(MySqlSIARDDKTest.java:242)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
[main] DEBUG 2016-02-12 15:30:40,875 (Main) #########################################################

````

**Comment by ThomasKristensen** [comment]
@andreaskring  The commit-id below implements reading utf-8 strings encoded in hexBinary during import of siard-dk archive. However the issue can first be closed when `xs:hexBinary` is no longer returned from `convert` in `SIARDDKsql99ToXsdType`.

9134d721c7ee33ccb42336e246b8b903827e4d90

**Comment by andreaskring** [comment]
Fixed in https://github.com/keeps/db-preservation-toolkit/pull/144

**Comment by andreaskring** [comment]
@chalkos This issue can be closed

**Comment by chalkos** [comment]
@andreaskring ok. If you have permissions to do it (I don't know if you do), feel free to close the ones that are only about SIARD-DK
