### ISSUE TITLE
NullPointerException when converting SIARD to MySQL

### ISSUE THREAD

**Issue by luis100** [keeps/db-preservation-toolkit#16]
When round-trip testing from MySQL to SIARD and back again, the following error occurred on the SIARD to MySQL conversion:

```
ERROR 2014-12-04 17:03:32,931 (Main) Unexpected exception
java.lang.NullPointerException
	at pt.gov.dgarq.roda.common.convert.db.modules.jdbc.out.JDBCExportModule.handleDataCell(JDBCExportModule.java:637)
	at pt.gov.dgarq.roda.common.convert.db.modules.jdbc.out.JDBCExportModule.handleDataRow(JDBCExportModule.java:526)
	at pt.gov.dgarq.roda.common.convert.db.modules.siard.in.SIARDImportModule$SIARDContentSAXHandler.endElement(SIARDImportModule.java:953)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
	at pt.gov.dgarq.roda.common.convert.db.modules.siard.in.SIARDImportModule.getDatabase(SIARDImportModule.java:224)
	at pt.gov.dgarq.roda.common.convert.db.Main.main(Main.java:89)
```

**Comment by chalkos** [comment]
Must have been fixed when the roundtrip system was changed. Could not reproduce it now.
