### ISSUE TITLE
PostgreSQL: a table stored in the wrong schema

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#162]
Description: A database with tables in two schemas were captured into a siard file. During restoring an error occured - one table was restored into the wrong schema.

Steps required to reproduce the bug:

1. Input:
    database test_a
         schema: public   (tables: arhiv_log, tabela1)
         schema: sch_testb (table: users)
2. use dbptk-app-2.0.0-beta4.0.jar  to create the package and then restore
3. The error is:
INFO [13:11:08] Exporting data for public.arhiv_log
INFO [13:11:11] Exporting data for public.tabela1
INFO [13:11:11] Exporting data for sch_testb.users
ERROR [13:11:11] An error occurred while handling data close table
                 Error granting permissions to public
                 ERROR: relation "sch_testb.users" does not exist
4. Output:
    database eark_testA
         schema: public   (tables: arhiv_log, tabela1, users))
         schema: sch_testb (tables:         )

Attach the dbptk-app.log.txt file below.
DEBUG 2016-03-18 13:11:11,603 (JDBCExportModule) sql: INSERT INTO "users" VALUES (?)
DEBUG 2016-03-18 13:11:11,603 (SIARD1ContentImportStrategy) before handle data close
ERROR 2016-03-18 13:11:11,604 (SIARD1ContentImportStrategy) An error occurred while handling data close table
                 Error granting permissions to public
                 ERROR: relation "sch_testb.users" does not exist

**Comment by chalkos** [comment]
@BorisDomajnko could you test this with beta4.3 and check if the behaviour is similar to the one in #163 ?

**Comment by BorisDomajnko** [comment]
v2.0.0-beta4.3:
tables:
   public.arhiv_log
   public.tabela1
   sch_testa.users

restore to PostgreSQL - all three tables were created in "public", but the third one was supposed to be in "sch_testa"!

     Converting database: siard-2 to postgresql
     Target database does not exist. Creating database eark_testA
     Exporting database structure
     Exporting schema structure for schema public
     Exporting table structure for arhiv_log
     Exporting table structure for tabela1
     Exporting schema structure for schema public
     Exporting schema structure for schema sch_testa
     Exporting table structure for users
     Exporting schema structure for schema sch_testa
     Exporting database structure finished
     Obtaining contents from table 'public.arhiv_log'
     Exporting content to table for public.arhiv_log
     Total of 11197 row(s) processed
     Obtained contents from table 'public.arhiv_log'
     Obtaining contents from table 'public.tabela1'
     Exporting content to table for public.tabela1
     Total of 2239 row(s) processed
     Obtained contents from table 'public.tabela1'
     Obtaining contents from table 'sch_testa.users'
     Exporting content to table for sch_testa.users
     Total of 2 row(s) processed
ERROR Error granting public read access permissions on table sch_testa.users
ERROR Error closing table sch_testa.users
     Obtained contents from table 'sch_testa.users'
     Adding foreign keys for table public.arhiv_log
     Adding foreign keys for table public.tabela1
     Adding foreign keys for table sch_testa.users
     Finished adding foreign keys
     Run time 0m 3s
     A report was generated with a listing of information that was modified during the conversion.
     The report file is located at d:\projekti\E-ARK\dbptk-report-20160531100140584.txt
     Please report any problems at https://github.com/keeps/db-preservation-toolkit/issues/new

dbptk-app.log.txt:

2016-05-31 10:01:44,133 [main] DEBUG (c.d.m.j.o.JDBCExportModule) sql: INSERT INTO "tabela1" VALUES (?, ?, ?, ?)
2016-05-31 10:01:44,340 [main] INFO  (c.d.m.s.i.c.SIARD2ContentImportStrategy) Total of 2239 row(s) processed
2016-05-31 10:01:44,344 [main] INFO  (c.d.m.s.i.c.SIARD2ContentImportStrategy) Obtained contents from table 'public.tabela1'
2016-05-31 10:01:44,347 [main] INFO  (c.d.m.s.i.c.SIARD2ContentImportStrategy) Obtaining contents from table 'sch_testa.users'
2016-05-31 10:01:44,347 [main] DEBUG (c.d.m.j.o.JDBCExportModule) Started data open: sch_testa.users
2016-05-31 10:01:44,347 [main] INFO  (c.d.m.j.o.JDBCExportModule) Exporting content to table for sch_testa.users
2016-05-31 10:01:44,348 [main] DEBUG (c.d.m.j.o.JDBCExportModule) sql: INSERT INTO "users" VALUES (?, ?)
2016-05-31 10:01:44,348 [main] INFO  (c.d.m.s.i.c.SIARD2ContentImportStrategy) Total of 2 row(s) processed
2016-05-31 10:01:44,352 [main] ERROR (c.d.m.p.o.PostgreSQLJDBCExportModule) Error granting public read access permissions on table sch_testa.users
org.postgresql.util.PSQLException: ERROR: relation "sch_testa.users" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:321)
	at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:297)
	at com.databasepreservation.modules.postgreSql.out.PostgreSQLJDBCExportModule.handleDataCloseTable(PostgreSQLJDBCExportModule.java:162)
	at com.databasepreservation.modules.siard.in.content.SIARD2ContentImportStrategy.endElement(SIARD2ContentImportStrategy.java:278)

**Comment by chalkos** [comment]
Thanks @BorisDomajnko

**Comment by chalkos** [comment]
Fixed by #216
