### ISSUE TITLE
Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by dglab-arquivos** [keeps/db-preservation-toolkit#172]
Description: Importing to mysql siard2 file from mssql fails
mssql 2008 R2
mysql 5.5.47 on ubuntu 14.04.1

Digitarq Database export.

```
DEBUG 2016-03-30 16:55:27,316 (JDBCExportModule) SQL: ALTER TABLE `UsersProfiles` ADD CONSTRAINT `PK_UsersProfiles` PRIMARY KEY (`Username`, `ProfileName`)
INFO 2016-03-30 16:55:27,316 (JDBCExportModule) Handling schema structure dbo finished
DEBUG 2016-03-30 16:55:27,316 (JDBCExportModule) Executing table creation batch
ERROR 2016-03-30 16:55:28,004 (JDBCExportModule) Error creating structure (next exception)
                 Specified key was too long; max key length is 767 bytes
DEBUG 2016-03-30 16:55:28,005 (JDBCExportModule) Error creating structure (next exception)
                 Specified key was too long; max key length is 767 bytes
java.sql.BatchUpdateException: Specified key was too long; max key length is 767 bytes
	at com.mysql.jdbc.StatementImpl.executeBatchUsingMultiQueries(StatementImpl.java:1268)
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:1063)
	at com.databasepreservation.modules.jdbc.out.JDBCExportModule.handleStructure(JDBCExportModule.java:279)
	at com.databasepreservation.modules.siard.in.input.SIARDImportDefault.getDatabase(SIARDImportDefault.java:43)
	at com.databasepreservation.Main.run(Main.java:121)
	at com.databasepreservation.Main.internal_main(Main.java:78)
	at com.databasepreservation.Main.main(Main.java:60)
ERROR 2016-03-30 16:55:28,006 (Main) Error while importing/exporting
                 Error creating structure
                 Specified key was too long; max key length is 767 bytes
DEBUG 2016-03-30 16:55:28,006 (Main) Error while importing/exporting
                 Error creating structure
                 Specified key was too long; max key length is 767 bytes
com.databasepreservation.model.exception.ModuleException: Error creating structure
	at com.databasepreservation.modules.jdbc.out.JDBCExportModule.handleStructure(JDBCExportModule.java:298)
	at com.databasepreservation.modules.siard.in.input.SIARDImportDefault.getDatabase(SIARDImportDefault.java:43)
	at com.databasepreservation.Main.run(Main.java:121)
	at com.databasepreservation.Main.internal_main(Main.java:78)
	at com.databasepreservation.Main.main(Main.java:60)
Caused by: java.sql.BatchUpdateException: Specified key was too long; max key length is 767 bytes
	at com.mysql.jdbc.StatementImpl.executeBatchUsingMultiQueries(StatementImpl.java:1268)
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:1063)
	at com.databasepreservation.modules.jdbc.out.JDBCExportModule.handleStructure(JDBCExportModule.java:279)
	... 4 more
DEBUG 2016-03-30 16:55:28,007 (Main) #########################################################
DEBUG 2016-03-30 16:55:28,007 (Main) #   FINISH-ID-a96d8c0b-4af9-4728-8504-2c23d41a408f
DEBUG 2016-03-30 16:55:28,007 (Main) #   FINISH v2.0.0-beta4.0
DEBUG 2016-03-30 16:55:28,007 (Main) #   EXIT CODE: 1
DEBUG 2016-03-30 16:55:28,007 (Main) #########################################################
```

**Comment by chalkos** [comment]
It seems that this has to do with limitations on the target database ("Specified key was too long; max key length is 767 bytes").

I will make it so that in this case the primary key is not created and a warning is shown.
