### ISSUE TITLE
Postgresql: error with table name with upper letter

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#239]
Description: 
2.0.0.-beta5

1. the original table name has upper letters (regust.upravna_enotaOLD), 
2. creation of siard file: the error occurs.

Attach the dbptk-app.log.txt file below.
2016-08-02 14:46:23,067 [main] DEBUG (c.d.m.Reporter) dataTypeChangedOnImport, invoker: com.databasepreservation.modules.postgreSql.in.PostgreSQLJDBCDatatypeImporter; message: - Type conversion in import module: in `regust.upravna_enotaOLD.datum_kon_velj` (format: schema.table.column) has original type `DATE` and was converted to the standard type `DATE`; and type: Type{description='null', originalTypeName='date', sql99TypeName='DATE', sql2008TypeName='DATE'}
2016-08-02 14:46:23,067 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Data type: 91
Type name: date
Column size: 13
Decimal digits: 0
Radix: 10
Remarks: null
Default value: null
Index: 5
Is Nullable: true
Is auto increment: false
Calculated type: SimpleTypeDateTime
ColumnType hash: 1223581419

2016-08-02 14:46:23,087 [main] DEBUG (c.d.m.j.i.JDBCImportModule) count query: SELECT COUNT(*) FROM "regust"."upravna_enotaold"
2016-08-02 14:46:23,097 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Closing connection to source database
2016-08-02 14:46:23,097 [main] ERROR (c.d.Main) Connection error while importing/exporting
com.databasepreservation.model.exception.ModuleException: SQL error while connecting
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1565)

**Comment by chalkos** [comment]
Can you try this version: 
[dbptk-app-2.0.0-SNAPSHOT-246-1.zip](https://github.com/keeps/db-preservation-toolkit/files/412986/dbptk-app-2.0.0-SNAPSHOT-246-1.zip)

It should fix this problem as well as #238

**Comment by BorisDomajnko** [comment]
(outdated reply, also in mails 11.Aug.))
-e list-tables works but -e siard-2 reports error:
2016-08-18 13:46:09,942 [main] DEBUG (c.d.m.j.i.JDBCImportModule) count query: SELECT COUNT(*) FROM "sch_testA"."users"
2016-08-18 13:46:09,943 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Counted 2 rows
2016-08-18 13:46:09,955 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Database structure obtained
2016-08-18 13:46:09,955 [main] INFO  (c.d.m.j.i.JDBCImportModule) Database structure converted
2016-08-18 13:46:09,956 [main] INFO  (c.d.m.j.i.JDBCImportModule) Getting contents from table 'public.arhiv_log'
2016-08-18 13:46:09,957 [main] DEBUG (c.d.m.p.i.PostgreSQLJDBCImportModule) query: SELECT tabela, polje, vrednost, vrsta, sprememba, uporabnik, datum FROM public.arhiv_log
2016-08-18 13:46:10,779 [main] INFO  (c.d.m.j.i.JDBCImportModule) Total of 11197 row(s) processed
2016-08-18 13:46:10,781 [main] INFO  (c.d.m.j.i.JDBCImportModule) Obtained contents from table 'public.arhiv_log'
2016-08-18 13:46:10,781 [main] INFO  (c.d.m.j.i.JDBCImportModule) Getting contents from table 'public.tabela1'
2016-08-18 13:46:10,781 [main] DEBUG (c.d.m.p.i.PostgreSQLJDBCImportModule) query: SELECT num1, num2, str1, bool1 FROM public.tabela1
2016-08-18 13:46:10,844 [main] INFO  (c.d.m.j.i.JDBCImportModule) Total of 2239 row(s) processed
2016-08-18 13:46:10,863 [main] INFO  (c.d.m.j.i.JDBCImportModule) Obtained contents from table 'public.tabela1'
2016-08-18 13:46:10,864 [main] INFO  (c.d.m.j.i.JDBCImportModule) Getting contents from table 'sch_testA.users'
2016-08-18 13:46:10,864 [main] DEBUG (c.d.m.p.i.PostgreSQLJDBCImportModule) query: SELECT id, name FROM sch_testA.users
2016-08-18 13:46:10,865 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Closing connection to source database
2016-08-18 13:46:10,866 [main] ERROR (c.d.Main) Connection error while importing/exporting
com.databasepreservation.model.exception.ModuleException: SQL error while connecting
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1565)
	at com.databasepreservation.Main.run(Main.java:126)
	at com.databasepreservation.Main.internal_main(Main.java:84)
	at com.databasepreservation.Main.main(Main.java:62)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "sch_testa.users" does not exist
  Position: 22
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:321)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:284)
	at com.databasepreservation.modules.postgreSql.in.PostgreSQLJDBCImportModule.getTableRawData(PostgreSQLJDBCImportModule.java:168)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1538)
	... 3 common frames omitted
2016-08-18 13:46:10,866 [main] ERROR (c.d.Main) Fatal error while converting the database (SQL error while connecting)
com.databasepreservation.model.exception.ModuleException: SQL error while connecting
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1565)
	at com.databasepreservation.Main.run(Main.java:126)
	at com.databasepreservation.Main.internal_main(Main.java:84)
	at com.databasepreservation.Main.main(Main.java:62)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "sch_testa.users" does not exist
  Position: 22
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:321)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:284)
	at com.databasepreservation.modules.postgreSql.in.PostgreSQLJDBCImportModule.getTableRawData(PostgreSQLJDBCImportModule.java:168)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1538)
	... 3 common frames omitted
2016-08-18 13:46:10,867 [main] INFO  (c.d.m.Reporter) A report was generated with a listing of information that was modified during the conversion.
2016-08-18 13:46:10,868 [main] INFO  (c.d.m.Reporter) The report file is located at d:\projekti\E-ARK\dbptk-report-20160818134607986.txt
2016-08-18 13:46:10,868 [main] INFO  (c.d.Main) Please report any problems at https://github.com/keeps/db-preservation-toolkit/issues/new
2016-08-18 13:46:10,868 [main] DEBUG (c.d.Main) #########################################################
2016-08-18 13:46:10,868 [main] DEBUG (c.d.Main) #   FINISH-ID-34afd5fb-32a2-42d2-b1be-8871f487ba87
2016-08-18 13:46:10,868 [main] DEBUG (c.d.Main) #   FINISH v2.0.0-SNAPSHOT-246-1
2016-08-18 13:46:10,868 [main] DEBUG (c.d.Main) #   EXIT CODE: 4
2016-08-18 13:46:10,868 [main] DEBUG (c.d.Main) #########################################################

**Comment by chalkos** [comment]
I believe this is exactly the same error you posted on #238.

This issue is so similar to #238 that I will just close this one and fix both in #238.
