### ISSUE TITLE
Error converting data from SIARD to MSSQLServer

### ISSUE THREAD

**Issue by luis100** [keeps/db-preservation-toolkit#24]
When converting from SIARD to MSSQLServer the following error occurred:
```
ERROR 2014-12-04 18:19:50,977 (SIARDImportModule) An error occurred while handling data row
pt.gov.dgarq.roda.common.convert.db.model.exception.ModuleException: Error executing insert batch
	at pt.gov.dgarq.roda.common.convert.db.modules.jdbc.out.JDBCExportModule.handleDataRow(JDBCExportModule.java:540)
	at pt.gov.dgarq.roda.common.convert.db.modules.siard.in.SIARDImportModule$SIARDContentSAXHandler.endElement(SIARDImportModule.java:953)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
	at pt.gov.dgarq.roda.common.convert.db.modules.siard.in.SIARDImportModule.getDatabase(SIARDImportModule.java:224)
	at pt.gov.dgarq.roda.common.convert.db.Main.main(Main.java:89)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The stream value is not the specified length. The specified length was 4,241, the actual length is 4,198.
	at com.microsoft.sqlserver.jdbc.TDSWriter.error(IOBuffer.java:3426)
	at com.microsoft.sqlserver.jdbc.TDSWriter.writeReader(IOBuffer.java:3418)
	at com.microsoft.sqlserver.jdbc.TDSWriter.writeRPCReaderUnicode(IOBuffer.java:4641)
	at com.microsoft.sqlserver.jdbc.DTV$SendByRPCOp.execute(dtv.java:887)
	at com.microsoft.sqlserver.jdbc.DTV.executeOp(dtv.java:1078)
	at com.microsoft.sqlserver.jdbc.DTV.sendByRPC(dtv.java:1116)
	at com.microsoft.sqlserver.jdbc.Parameter.sendByRPC(Parameter.java:660)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.sendParamsByRPC(SQLServerPreparedStatement.java:473)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doPrepExec(SQLServerPreparedStatement.java:628)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatementBatch(SQLServerPreparedStatement.java:1282)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtBatchExecCmd.doExecute(SQLServerPreparedStatement.java:1209)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:1173)
	at pt.gov.dgarq.roda.common.convert.db.modules.jdbc.out.JDBCExportModule.handleDataRow(JDBCExportModule.java:535)
	... 14 more
```

**Comment by chalkos** [comment]
Could not reproduce. It may already been fixed, otherwise I will need more information about the database.
