### ISSUE TITLE
PostgreSQL import module can not handle bit varying

### ISSUE THREAD

**Issue by chalkos** [keeps/db-preservation-toolkit#265]
Description: PostgreSQL is incapable of handling the (or a specific configuration of the) BIT VARYING type.

Steps required to reproduce the bug:

**1 .** Use the following SQL to create a problematic table:
```
create table bitVarying (id int primary key, b BIT VARYING(5));
insert into bitvarying values (0,B'101');
```
**2 .** Export the postgresql database to SIARD 2 to produce this error:

```
2016-09-12 12:32:09,715 [main] DEBUG (c.d.m.j.i.JDBCDatatypeImporter) Unsupported JDBC type, code: 1111
2016-09-12 12:32:09,715 [main] DEBUG (c.d.m.Reporter) customMessage, invoker: com.databasepreservation.modules.postgreSql.in.PostgreSQLJDBCDatatypeImporter; message: - Possibility of incomplete type definition: Could not determine SQL99 type for varbit
2016-09-12 12:32:09,715 [main] DEBUG (c.d.m.Reporter) customMessage, invoker: com.databasepreservation.modules.postgreSql.in.PostgreSQLJDBCDatatypeImporter; message: - Possibility of incomplete type definition: Could not determine SQL2008 type for varbit
2016-09-12 12:32:09,715 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Closing connection to source database
2016-09-12 12:32:09,715 [main] ERROR (c.d.Main) Fatal error: Unexpected exception (null)
java.lang.NullPointerException: null
        at com.databasepreservation.model.Reporter.dataTypeChangedOnImport(Reporter.java:253)
        at com.databasepreservation.model.modules.DatatypeImporter.checkType(DatatypeImporter.java:97)
        at com.databasepreservation.model.modules.DatatypeImporter.getCheckedType(DatatypeImporter.java:71)
        at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getColumn(JDBCImportModule.java:803)
        at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getColumns(JDBCImportModule.java:701)
        at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getTableStructure(JDBCImportModule.java:504)
        at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getTables(JDBCImportModule.java:425)
        at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getSchemaStructure(JDBCImportModule.java:302)
        at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getSchemas(JDBCImportModule.java:269)
        at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabaseStructure(JDBCImportModule.java:220)
        at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1493)
        at com.databasepreservation.Main.run(Main.java:127)
        at com.databasepreservation.Main.internal_main(Main.java:80)
        at com.databasepreservation.Main.main(Main.java:62)
```

Reported by @andreaskring in #250

**Comment by chalkos** [comment]
@andreaskring this fix is specific to postgresql, it is that way because the postgresql driver is not very good at handling binary data (that is what caused the problem to exist in the first place).

**Comment by andreaskring** [comment]
@chalkos  Thank you for fixing this

**Comment by andreaskring** [comment]
@chalkos Just tested the fix. When exporting the database above containing BIT VARYING, the SQL datatype is set to BINARY VARYING - but it should be set to BIT VARYING? (or am I misunderstanding something)

**Comment by chalkos** [comment]
You make a good point. It should be BIT VARYING for SQL99 (in which BINARY VARYING does not exist), it should be BINARY VARYING for SQL2008 (in which BIT VARYING does not exist). Both support BINARY LARGE OBJECT, although using that type would loose the size.

Since there is a common type, I'll be using that one (i.e. BINARY LARGE OBJECT). Unless you have something else in mind..

**Comment by andreaskring** [comment]
I had a talk with @chalkos about this on Skype, and just for completeness I will update this issue with what we agreed on. In SIARDDK it is mandatory to convert all BLOBs to files, so we decided to set the SQL99 type to BIT VARYING. @chalkos guided me on how to fix this on the import side of the code, and the changes will be added to the pull request #261
