### ISSUE TITLE
Bug in converting siard-dk package

### ISSUE THREAD

**Issue by poullc** [keeps/db-preservation-toolkit#324]
I have installed the latest DBVTK on an Ubunt 12 server and the installation seems to work fine and Solr is running too.

When I run this command as root, I get “Fatal error: Unexpected exception (null)"

"/opt/dbvtk/jre/linux/bin/java" -jar "-Dfile.encoding=UTF-8" "-Ddbvtk.home=/opt/dbvtk/dbvtk-data" "/opt/dbvtk/dbptk-app.jar" -e solr -eh localhost -ep 8983 -edbid 0plc -i siard-dk -ias public -if "/opt/dbvtk/siard/AVID.RALS.95000.1"
     Converting database: siard-dk to Solr
ERROR Fatal error: Unexpected exception (null)
     Troubleshooting information can be found at http://www.database-preservation.com/#troubleshooting
     Please report any problems at https://github.com/keeps/db-preservation-toolkit/issues/new

I tried removing the optional parameters " -eh localhost -ep 8983 -edbid 0plc”, but it didn’t make any difference.

When I export my Siard-dk file with module list-tables, it works just fine.

From the log file:
`2017-11-09 11:18:46,292 [main] DEBUG (c.d.m.s.i.m.t.SQL99StandardDatatypeImporter) name: DOUBLE PRECISION, stdType: SqlStandardType{original='DOUBLE PRECISION', normalized='DOUBLE PRECISION', isValid=true, base='DOUBLE PRECISION', hasTimezoneInfo=false, includesTimezone=false, typeTimezonePart='', hasColumnSize=false, columnSize=0, hasDecimaldigits=false, decimalDigits=0, isArray=false, hasArrayLength=false, arrayLength=0}
2017-11-09 11:18:46,303 [main] ERROR (c.d.Main) Fatal error: Unexpected exception (null)
java.lang.NullPointerException: null
       at com.databasepreservation.visualization.transformers.ToolkitStructure2ViewerStructure.getColumns(ToolkitStructure2ViewerStructure.java:440)
       at com.databasepreservation.visualization.transformers.ToolkitStructure2ViewerStructure.getView(ToolkitStructure2ViewerStructure.java:257)
       at com.databasepreservation.visualization.transformers.ToolkitStructure2ViewerStructure.getViews(ToolkitStructure2ViewerStructure.java:247)
       at com.databasepreservation.visualization.transformers.ToolkitStructure2ViewerStructure.getSchema(ToolkitStructure2ViewerStructure.java:235)
       at com.databasepreservation.visualization.transformers.ToolkitStructure2ViewerStructure.getSchemas(ToolkitStructure2ViewerStructure.java:222)
       at com.databasepreservation.visualization.transformers.ToolkitStructure2ViewerStructure.getMetadata(ToolkitStructure2ViewerStructure.java:146)
       at com.databasepreservation.visualization.transformers.ToolkitStructure2ViewerStructure.getDatabase(ToolkitStructure2ViewerStructure.java:120)
       at com.databasepreservation.modules.solr.SolrExportModule.handleStructure(SolrExportModule.java:102)
       at com.databasepreservation.modules.siard.in.input.SIARDImportDefault.getDatabase(SIARDImportDefault.java:50)
       at com.databasepreservation.Main.run(Main.java:161)
       at com.databasepreservation.Main.internal_main(Main.java:108)
       at com.databasepreservation.Main.main(Main.java:86)
2017-11-09 11:18:46,303 [main] INFO  (c.d.Main) Troubleshooting information can be found at http://www.database-preservation.com/#troubleshooting
2017-11-09 11:18:46,303 [main] INFO  (c.d.Main) Please report any problems at https://github.com/keeps/db-preservation-toolkit/issues/new
2017-11-09 11:18:46,304 [main] DEBUG (c.d.Main) #########################################################
2017-11-09 11:18:46,304 [main] DEBUG (c.d.Main) #   FINISH-ID-dc5de37f-84ef-4721-b605-1a6cc9da958b
2017-11-09 11:18:46,304 [main] DEBUG (c.d.Main) #   FINISH v2.0.0
2017-11-09 11:18:46,304 [main] DEBUG (c.d.Main) #   EXIT CODE: 1
2017-11-09 11:18:46,304 [main] DEBUG (c.d.Main) #########################################################`

I cannot provide the siard-dk package.

**Comment by chalkos** [comment]
The solr module is optimized to get data from the SIARD2 module, maybe the siard-dk module is not providing all the necessary information.

Can you try converting the siard-dk file to siard2 and export it to solr?

**Comment by poullc** [comment]
Ok, when I try to convert it to siard2 I get this error in the log (+ a partial 156MB siard2 file):

`2017-11-09 15:29:32,332 [main] DEBUG (c.d.m.s.i.c.SIARDDKContentImportStrategy) begin parse of xml-file:[Tables/table28/table28.xml], using xsd [Tables/table28/table28.xsd]
2017-11-09 15:29:32,424 [main] DEBUG (c.d.m.s.i.c.SIARDDKContentImportStrategy) begin parse of xml-file:[Tables/table29/table29.xml], using xsd [Tables/table29/table29.xsd]
2017-11-09 15:29:32,823 [main] ERROR (c.d.Main) Fatal error while converting the database (Error while Marshalling JAXB)
com.databasepreservation.model.exception.ModuleException: Error while Marshalling JAXB
        at com.databasepreservation.modules.siard.out.metadata.SIARD2MetadataExportStrategy.writeMetadataXML(SIARD2MetadataExportStrategy.java:150)
        at com.databasepreservation.modules.siard.out.output.SIARDExportDefault.finishDatabase(SIARDExportDefault.java:195)
        at com.databasepreservation.modules.siard.in.input.SIARDImportDefault.getDatabase(SIARDImportDefault.java:56)
        at com.databasepreservation.Main.run(Main.java:161)
        at com.databasepreservation.Main.internal_main(Main.java:108)
        at com.databasepreservation.Main.main(Main.java:86)
Caused by: javax.xml.bind.MarshalException: null
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:311)
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:236)
        at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:95)
        at com.databasepreservation.modules.siard.out.metadata.SIARD2MetadataExportStrategy.writeMetadataXML(SIARD2MetadataExportStrategy.java:147)
        ... 5 common frames omitted
Caused by: org.xml.sax.SAXParseException: cvc-complex-type.2.4.b: The content of element 'view' is not complete. One of '{"http://www.bar.admin.ch/xmlns/siard/2.0/metadata.xsd":columns}' is expected.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:452)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3230)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.elementLocallyValidComplexType(XMLSchemaValidator.java:3206)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.elementLocallyValidType(XMLSchemaValidator.java:3153)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.processElementContent(XMLSchemaValidator.java:3055)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleEndElement(XMLSchemaValidator.java:2134)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.endElement(XMLSchemaValidator.java:853)
        at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorHandlerImpl.endElement(ValidatorHandlerImpl.java:584)
        at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
        at com.sun.xml.internal.bind.v2.runtime.output.SAXOutput.endTag(SAXOutput.java:117)
        at com.sun.xml.internal.bind.v2.runtime.output.XmlOutputAbstractImpl.endTag(XmlOutputAbstractImpl.java:109)
        at com.sun.xml.internal.bind.v2.runtime.output.ForkXmlOutput.endTag(ForkXmlOutput.java:76)
        at com.sun.xml.internal.bind.v2.runtime.output.NamespaceContextImpl$Element.endElement(NamespaceContextImpl.java:489)
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.endElement(XMLSerializer.java:300)
        at com.sun.xml.internal.bind.v2.runtime.property.ArrayElementProperty.serializeListBody(ArrayElementProperty.java:160)
        at com.sun.xml.internal.bind.v2.runtime.property.ArrayERProperty.serializeBody(ArrayERProperty.java:144)
        at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.serializeBody(ClassBeanInfoImpl.java:345)
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.childAsXsiType(XMLSerializer.java:681)
        at com.sun.xml.internal.bind.v2.runtime.property.SingleElementNodeProperty.serializeBody(SingleElementNodeProperty.java:143)
        at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.serializeBody(ClassBeanInfoImpl.java:345)
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.childAsXsiType(XMLSerializer.java:681)
        at com.sun.xml.internal.bind.v2.runtime.property.ArrayElementNodeProperty.serializeItem(ArrayElementNodeProperty.java:54)
        at com.sun.xml.internal.bind.v2.runtime.property.ArrayElementProperty.serializeListBody(ArrayElementProperty.java:157)
        at com.sun.xml.internal.bind.v2.runtime.property.ArrayERProperty.serializeBody(ArrayERProperty.java:144)
        at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.serializeBody(ClassBeanInfoImpl.java:345)
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.childAsXsiType(XMLSerializer.java:681)
        at com.sun.xml.internal.bind.v2.runtime.property.SingleElementNodeProperty.serializeBody(SingleElementNodeProperty.java:143)
        at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.serializeBody(ClassBeanInfoImpl.java:345)
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.childAsSoleContent(XMLSerializer.java:578)
        at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.serializeRoot(ClassBeanInfoImpl.java:326)
        at com.sun.xml.internal.bind.v2.runtime.XMLSerializer.childAsRoot(XMLSerializer.java:479)
        at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:308)
        ... 8 common frames omitted
2017-11-09 15:29:32,824 [main] INFO  (c.d.Main) Troubleshooting information can be found at http://www.database-preservation.com/#troubleshooting
2017-11-09 15:29:32,824 [main] INFO  (c.d.Main) Please report any problems at https://github.com/keeps/db-preservation-toolkit/issues/new
2017-11-09 15:29:32,824 [main] DEBUG (c.d.Main) #########################################################
2017-11-09 15:29:32,824 [main] DEBUG (c.d.Main) #   FINISH-ID-b3bfcdd5-e9d5-40ed-bf15-1c43db5661dd
2017-11-09 15:29:32,824 [main] DEBUG (c.d.Main) #   FINISH v2.0.0
2017-11-09 15:29:32,824 [main] DEBUG (c.d.Main) #   EXIT CODE: 1
2017-11-09 15:29:32,824 [main] DEBUG (c.d.Main) #########################################################`

**Comment by chalkos** [comment]
It seems that the SIARD-DK import module is not honoring some code compromise and is providing other modules with a `null` value when it should be an empty list.

To use the viewer, you can try to convert the original database to SIARD2 (if you still have the original database) and then convert the SIARD2 to the DBVTK.

Until this is fixed I dont believe the DBPTK will be able to convert that specific database to anything else (but as far as I can tell, the problem is in the application and not the in the siard-dk file).
