### ISSUE TITLE
Possible bug in sql-server module, failing to import triggers.

### ISSUE THREAD

**Issue by DavidUnderdown** [keeps/db-preservation-toolkit#325]
Description: 
Running trial conversion for the PRONOM database (SQL Server 2012, although database still actually SQL Server 2005), for each table get error reported 

```
"No triggers imported for <table> com.microsoft.sqlserver.jdbc.SQLServerException: Unclosed quotation mark after the character string '<table>'.
```

Steps required to reproduce the bug:
Run basic conversion with parameters indicated in log

Attach the dbptk-app.log.txt file below.  I've trimmed the log to a single table example, (and filtered a few more connection details that are considered sensitive).  I was using an account with admin rights on the database, but not a system administrator type account.  It is the same account used when we add new data to the PRONOM database.

[dbptk-app.log.trimmed.txt](https://github.com/keeps/db-preservation-toolkit/files/1527676/dbptk-app.log.trimmed.txt)

**Comment by luis100** [comment]
@DavidUnderdown will it be possible to get the PRONOM database so we can test it here?

**Comment by DavidUnderdown** [comment]
Possibly (the data is all openly published), but I will have to check.

**Comment by DavidUnderdown** [comment]
I will be able to provide a database backup - I need to do a little bit of sanitisation first though.  I don't particularly want to attach it here as we don't routinely publish the full database directly (the PRONOM data is obviously available through our website), so can I email it or Dropbox etc.  To be clear the backup would be made available purely for the investigation of this issue.

**Comment by luis100** [comment]
We just need a way to reproduce the problem, you can send us another example if you can produce it, but if not be assured that we will only use it to solve the this issue. You can send it to me lfaria@keep.pt

**Comment by DavidUnderdown** [comment]
Sorry for the delay, some other urgent work (and Christmas) got in the way.  I've just re-run the export, this time using credentials with sa rights, and there was no problem with the triggers this time, so it looks like it was permissions related.  I can still try to send through the database backup if you'd like to investigate further?

**Comment by DavidUnderdown** [comment]
Sorry for the delay (other urgent work and Christmas).  I've just re-run with sa credentials, and initially thought that was OK, but looking in the log rather than the report shows that the error message about triggers is still there.  I will try and send through the database later.  Would a backup be OK (from SQL 2012) it would it be better to send the actual .mdf, .ndf and .ldf?

**Comment by PhillipTommerholt** [comment]
During the E-ARK project I also reported what I thought was an error that happened when DBPTK tried to export a trigger:
https://github.com/keeps/db-preservation-toolkit/issues/228 
It turned out it was permission related.
I am not sure whether this information is relevant, and if there might be a general problem with database user permissions and triggers or if I am derailing this issue - so please be critical of my observatory comment :-)

**Comment by DavidUnderdown** [comment]
Phillip thanks - I though I had searched for other trigger related issues but seem to have failed to find that one.  Those were the lines I was thinking on, however the database is owned by sa (we regularly restore this particular database from backup copied from another server, and the job steps include sp_changedbowner 'sa'), the export was not done with the actual sa account but with another account which is a member of the server-wide sysadmins role within SQL Server, which should give it exactly the same rights as the sa account.

**Comment by luis100** [comment]
@DavidUnderdown the backup would be better for us. We also think this is not permission related. This is probably due to some unexpected situation on the data that makes the generated SQL statement to fetch the triggers to be invalid and make the error you have found.

```
"No triggers imported for <table> com.microsoft.sqlserver.jdbc.SQLServerException: Unclosed quotation mark after the character string '<table>'.
```

**Comment by luis100** [comment]
@chalkos note that in [this line that generates the SQL Server Triggers SQL](https://github.com/keeps/db-preservation-toolkit/blob/master/dbptk-modules/dbptk-module-sql-server/src/main/java/com/databasepreservation/modules/sqlServer/SQLServerHelper.java#L150) the quote is not closed after the `tableName`.

**Comment by DavidUnderdown** [comment]
That looks promising.  I will try to sort the backup out tomorrow.

**Comment by chalkos** [comment]
@luis100 yep, that seems to be causing this error.

**Comment by DavidUnderdown** [comment]
Luis, I've just sent through the backup, zipped it's about 3.5 MB. It looks like you may have worked out the cause anyway.

**Comment by luis100** [comment]
@DavidUnderdown I haven't received the backup, but you're right, we might not need it after all if you could test the version attached (please rename it by removing the .zip extension).

[dbptk-app-2.0.0_lf_bug325.jar.zip](https://github.com/keeps/db-preservation-toolkit/files/1631443/dbptk-app-2.0.0_lf_bug325.jar.zip)

**Comment by luis100** [comment]
@DavidUnderdown if you test it and it works with no errors, can I ask you also to check if the triggers on the siard2.zip/header/metadata.xml are all there and correctly extracted? Cheer.

**Comment by DavidUnderdown** [comment]
@luis100 - I've been off sick most of the week, but I've had a quick look today and that does seem to have done the trick.  It's reporting 50 triggers in total, so I've not had chance to review them all in detail.  I'll have more of a look next week, but I'm on some training and things as well.

**Comment by DavidUnderdown** [comment]
@luis100 Finally had chance to go through in detail today.  It's actually 25 triggers (I accidentally counted the closing tags in the xml as well first time around).  The create statements in the xml are match what's generated by the database itself (once I'd got used to the escaping of carriage returns and various other things), and a query on the database itself confirms that 25 is the correct number of triggers.

I'm therefore happy that the fix resolves this issue for me.

**Comment by DavidUnderdown** [comment]
Doing a bit more work today I've noticed one odd thing appearing in the log file, this is an example from the output for the software_aliases table:

2018-01-30 15:32:24,820 [main] DEBUG (c.d.m.s.i.SQLServerJDBCImportModule) Trigger action time: 10
2018-01-30 15:32:24,820 [main] DEBUG (c.d.m.s.i.SQLServerJDBCImportModule) Trigger event: 110
2018-01-30 15:32:24,821 [main] DEBUG (c.d.m.j.i.JDBCImportModule) handled SQLException
com.microsoft.sqlserver.jdbc.SQLServerException: The column name REMARKS is not valid.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:190)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.findColumn(SQLServerResultSet.java:656)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getString(SQLServerResultSet.java:2401)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getTriggers(JDBCImportModule.java:1128)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getTableStructure(JDBCImportModule.java:533)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getTables(JDBCImportModule.java:449)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getSchemaStructure(JDBCImportModule.java:326)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getSchemas(JDBCImportModule.java:293)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabaseStructure(JDBCImportModule.java:244)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1609)
	at com.databasepreservation.Main.run(Main.java:161)
	at com.databasepreservation.Main.internal_main(Main.java:108)
	at com.databasepreservation.Main.main(Main.java:86)
2018-01-30 15:32:24,821 [main] DEBUG (c.d.m.s.i.SQLServerJDBCImportModule) Trigger action time: 10
2018-01-30 15:32:24,822 [main] DEBUG (c.d.m.s.i.SQLServerJDBCImportModule) Trigger event: 001
2018-01-30 15:32:24,822 [main] DEBUG (c.d.m.j.i.JDBCImportModule) handled SQLException
com.microsoft.sqlserver.jdbc.SQLServerException: The column name REMARKS is not valid.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:190)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.findColumn(SQLServerResultSet.java:656)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getString(SQLServerResultSet.java:2401)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getTriggers(JDBCImportModule.java:1128)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getTableStructure(JDBCImportModule.java:533)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getTables(JDBCImportModule.java:449)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getSchemaStructure(JDBCImportModule.java:326)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getSchemas(JDBCImportModule.java:293)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabaseStructure(JDBCImportModule.java:244)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1609)
	at com.databasepreservation.Main.run(Main.java:161)
	at com.databasepreservation.Main.internal_main(Main.java:108)
	at com.databasepreservation.Main.main(Main.java:86)

This message appears 25 times in the log, corresponding to the number of triggers, and occurs in the same tables which have triggers so it does seem to be related to outputting the triggers.  None of the tables have (so far as I can see) a REMARKS column, and none of the triggers refer to any such column so I don't quite understand what is going on here.

**Comment by chalkos** [comment]
It is not an error, just debug information. It is telling us that the REMARKS column (an internal column containing free-text descriptive metadata about the trigger) is not being exported because it was not where it was expected to be (maybe the SQL server does not support it, but I'm no expert in Microsoft SQL Server)

**Comment by DavidUnderdown** [comment]
OK, I noted the SQL Exception, but missed it was DEBUG message.  Looking at the sysobjects table there's certainly no remarks there.

**Comment by luis100** [comment]
@chalkos include fix on the next release

**Comment by chalkos** [comment]
Will do.
