### ISSUE TITLE
Possible bug in sql-server module, failing to get SQL for views

### ISSUE THREAD

**Issue by DavidUnderdown** [keeps/db-preservation-toolkit#327]
Description: 
For the 7 views in the PRONOM database, report is saying:
- Information: Could not obtain SQL statement for view [dbo].[v_file_extensions]
- Information: Could not obtain SQL statement for view [dbo].[v_format_generic_internal_signature_link]
- Information: Could not obtain SQL statement for view [dbo].[v_format_puids]
- Information: Could not obtain SQL statement for view [dbo].[v_format_specific_internal_signature_link]
- Information: Could not obtain SQL statement for view [dbo].[v_ipr_and_jurisdictions]
- Information: Could not obtain SQL statement for view [dbo].[v_ipr_and_owners]
- Information: Could not obtain SQL statement for view [dbo].[v_puids]

In SQL server management studio there is no problem obtaining a create script for the views.

Steps required to reproduce the bug:

1. Ran export, sql-server to SIARD2

Attach the dbptk-app.log.txt file below.
Have extracted one section for log.txt, the output for each view seems to be essentially the same:
```
2018-01-11 09:53:32,003 [main] DEBUG (c.d.m.s.i.SQLServerJDBCImportModule) Exception trying to get view SQL in SQL Server (method #2)
com.microsoft.sqlserver.jdbc.SQLServerException: The multi-part identifier "dbo.v_ipr_and_jurisdictions" could not be bound.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
	at com.databasepreservation.modules.sqlServer.in.SQLServerJDBCImportModule.getViews(SQLServerJDBCImportModule.java:211)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getSchemaStructure(JDBCImportModule.java:327)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getSchemas(JDBCImportModule.java:293)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabaseStructure(JDBCImportModule.java:244)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1609)
	at com.databasepreservation.Main.run(Main.java:161)
	at com.databasepreservation.Main.internal_main(Main.java:112)
	at com.databasepreservation.Main.main(Main.java:86)
2018-01-11 09:53:32,003 [main] DEBUG (c.d.m.Reporter) customMessage, invoker: SQLServerJDBCImportModule; message: - Information: Could not obtain SQL statement for view [dbo].[v_ipr_and_jurisdictions]
2018-01-11 09:53:32,004 [main] DEBUG (c.d.m.s.i.SQLServerJDBCImportModule) Exception trying to get view SQL in SQL Server (method #1)
com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near '@P0'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:285)
	at com.databasepreservation.modules.sqlServer.in.SQLServerJDBCImportModule.getViews(SQLServerJDBCImportModule.java:195)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getSchemaStructure(JDBCImportModule.java:327)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getSchemas(JDBCImportModule.java:293)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabaseStructure(JDBCImportModule.java:244)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1609)
	at com.databasepreservation.Main.run(Main.java:161)
	at com.databasepreservation.Main.internal_main(Main.java:112)
	at com.databasepreservation.Main.main(Main.java:86)
```

**Comment by DavidUnderdown** [comment]
I'm seeing this in another MSSQL database I'm currently looking at too.
