### ISSUE TITLE
Solution to JDBC connector to local instance of SQL Server

### ISSUE THREAD

**Issue by brianmatthewthomas** [keeps/db-preservation-toolkit#336]
Description: We had a local instance of SQL Server running to convert a very large (8GB) SQL dump. We did not have a password for the database, nor admin privileged but were instead trying to use windows integrated login to convert and received this message:

```
distracting security stuff
Caused by: java.lang.UnsatisfiedLinkError: no sqljdbc_auth in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at com.microsoft.sqlserver.jdbc.AuthenticationJNI.<clinit>(AuthenticationJNI.java:35)
	... 18 common frames omitted
2018-10-24 10:14:49,066 [main] INFO  (c.d.Main) Troubleshooting information can be found at http://www.database-preservation.com/#troubleshooting
2018-10-24 10:14:49,066 [main] INFO  (c.d.Main) Please report any problems at https://github.com/keeps/db-preservation-toolkit/issues/new
2018-10-24 10:14:49,066 [main] DEBUG (c.d.Main) #########################################################
2018-10-24 10:14:49,066 [main] DEBUG (c.d.Main) #   FINISH-ID-43b4fb6d-a81a-4cf7-8c16-bc287d1cbc15
2018-10-24 10:14:49,066 [main] DEBUG (c.d.Main) #   FINISH v2.0.0
2018-10-24 10:14:49,066 [main] DEBUG (c.d.Main) #   EXIT CODE: 4
2018-10-24 10:14:49,066 [main] DEBUG (c.d.Main) #########################################################
```

The problem was fixed by the detail at the end of the message, "no sqljdbc_auth in java.library.path"

Steps required to reproduce the bug:

1. DBPTK command:  java "-Dfile.encoding=UTF-8" "-Djavax.net.ssl.trustStore" -jar dbptk-app-2.0.0.jar -i microsoft-s
ql-server --import-server-name=[server name went here] --import-database=CTS --import-username=[windows admin username went here] --import-use-integrate
d-login --import-password=[password went here] -e siard-2 -ep -ef filename.siard
2. locate Microsoft JDBC Driver for SQL Server at https://www.microsoft.com/en-us/download/confirmation.aspx?id=11774.
3. After installing the JDBC driver make sure to copy sqljdbc_auth.dll into the ./bin directory of the installed version of java. In our case jre1.8.0_131.

[error-message.txt](https://github.com/keeps/db-preservation-toolkit/files/2534705/error-message.txt)

**Comment by chalkos** [comment]
Hey Brian! Thanks for sharing your solution.

If you don't mind, I will add this to the troubleshooting guide to make it easier to find.

**Comment by brianmatthewthomas** [comment]
I do not mind at all.

Brian Thomas
Electronic Records Specialist
Texas State Library and Archives Commission
1201 Brazos Street
Austin, TX 78701
PH: (512) 475-3374
e-mail: bthomas@tsl.texas.gov
tsl.texas.gov<http://tsl.texas.gov/>
[cid:image001.jpg@01D029A2.37194C70]

**Comment by chalkos** [comment]
Added to https://github.com/keeps/db-preservation-toolkit/wiki/Troubleshooting

**Comment by chalkos** [comment]
I also noticed that the driver being used has been discontinued, which might be why the login was not working. So this fix will probably not be needed after using a newer version of the driver.

Thanks again for finding the problem and a solution :+1:
