### ISSUE TITLE
Add support for Progress OpenEdge RDBMS

### ISSUE THREAD

**Issue by luis100** [keeps/db-preservation-toolkit#350]
Add a specific module for Progress OpenEdge RDBMS, bundle driver if permitted, test export of all database features.

**Comment by Laurira** [comment]
I tried to use jdbc driver for Progress database.

I found openedge.jar which should be sufficient for OpenEdge Release 11.1 (which I want to use).

**I tried the following command on Linux (allegedly the database has no password):**
jre1.8.0_201/bin/java  "-Dfile.encoding=UTF-8" -cp "dbptk-app-2.1.0.jar:openedge.jar" com.databasepreservation.Main --import=jdbc --import-driver=com.ddtek.jdbc.openedge.OpenEdgeDriver  --import-connection="jdbc:datadirect:openedge://localhost:20931;databaseName=postipoiss;user=ppoiss" -e siard-2 -ef postipoiss.siard

**I get the result**
      Converting database: jdbc to siard-2
      Initializing database
ERROR Fatal error while converting the database ([DataDirect][OpenEdge JDBC Driver]Software caused connection abort: recv failed.)
      Log files and migration reports were saved in /home/postipoiss/postipoissPreservation

**I attached the full log.**
Can you tell me what could be wrong.
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/2978749/dbptk-app.log.txt)

**Comment by chalkos** [comment]
From the log, it could be anything, really.... The driver is not doing a good job with error handling, since the error it does send is basically "expected to receive a network package but that did not happen".

This might by caused by incompatible driver/DBMS version, could not connect, could not authenticate...

**Comment by hmiguim** [comment]
Done in abe1cea82e7aeea8c63ffa1892d37fe5cf9e1fbc

**Comment by hmiguim** [comment]
To run the dbptk for progress openedge you have to specify the JDBC driver. Use this command:
java -cp "PATH_TO_THE_DBPTK_JAR.jar:PATH_TO_THE_PROGRESS_DRIVER.jar" com.databasepreservation.Main --import progress-openedge --import-hostname=localhost --import-database=dbname --import-username=username --import-password=password --import-port-number=port_number --export siard-2 --export-file=openedge.siard

**Comment by Laurira** [comment]
I entered a command and it just keeps thinking

![image](https://user-images.githubusercontent.com/3479156/57829217-ef0ef980-77b6-11e9-9742-53cb77ac97fe.png)

**Comment by Laurira** [comment]
Log is also not saying much more

**Import module:** progress-openedge
- hostname = localhost
- database = postipoiss
- username = root
- password = <filtered>
- port-number = 7842
2019-05-16 08:34:47,922 [main] DEBUG (c.d.m.Reporter) moduleParameters, module: siard-2 with parameters **Export module:** siard-2
- version = V2_1
- file = /home/postipoiss/postipoissPreservation/ppoiss.siard
- compress = false
- pretty-xml = false
- external-lobs = false
- external-lobs-per-folder = 1000
- external-lobs-folder-size = 0
- table-filter = null
2019-05-16 08:34:47,944 [main] INFO  (c.d.m.m.f.ProgressLoggerObserver) Initializing database
2019-05-16 08:34:47,953 [main] INFO  (c.d.m.s.o.o.SIARDExportDefault) Exporting SIARD version 2.1
2019-05-16 08:34:48,051 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Loading JDBC Driver com.ddtek.jdbc.openedge.OpenEdgeDriver
2019-05-16 08:34:48,142 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Getting connection

**Comment by Laurira** [comment]
I finally got the connection (our sysadmin decided to share correct credentials to me)

Now the siard file was created but there were lot of errors (Could not obtain all data from the current table) and warnings (... Some data may have been lost)

When I see the log then first error is this

```
2019-05-20 14:40:25,896 [main] DEBUG (c.d.m.j.i.JDBCImportModule) query: SELECT file, kirjeldus, kasutusel, moodul, ParentModule, create_kell, create_kpv, create_id, muutja_kell, muutja_kpv, muutja_id FROM PUB.moodul
2019-05-20 14:40:25,897 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Error executing query with default fetch size of 0
java.sql.SQLException: [DataDirect][OpenEdge JDBC Driver][OpenEdge] Syntax error in SQL statement at or about "file, kirjeldus, kasutusel, moodul, Pare" (10713)
	at com.ddtek.jdbc.openedge.client.dde.ac(Unknown Source)
	at com.ddtek.jdbc.openedge.client.dde.ab(Unknown Source)
	at com.ddtek.jdbc.openedge.ddf.a(Unknown Source)
	at com.ddtek.jdbc.openedge.ddf.b(Unknown Source)
	at com.ddtek.jdbc.openedgebase.ddek.v(Unknown Source)
	at com.ddtek.jdbc.openedgebase.ddek.u(Unknown Source)
	at com.ddtek.jdbc.openedgebase.ddek.executeQuery(Unknown Source)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getTableRawData(JDBCImportModule.java:1603)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getTableRawData(JDBCImportModule.java:1595)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.migrateDatabaseTo(JDBCImportModule.java:1710)
	at com.databasepreservation.DatabaseMigration.migrate(DatabaseMigration.java:96)
	at com.databasepreservation.Main.run(Main.java:147)
	at com.databasepreservation.Main.internalMain(Main.java:94)
	at com.databasepreservation.Main.main(Main.java:67)
```


Log file is big and I do not want to share it fully in public places as I am not aware if there could be something revealing or not. I can send it to you via e-mail if needed.

**Comment by Laurira** [comment]
Hi,

There is an issue with BETA2.
[ppoiss@pp postipoissPreservation]$ jre1.8.0_201/bin/java "-Dfile.encoding=UTF-8" -cp "dbptk-app-2.4.0-BETA2.jar:openedge.jar" com.databasepreservation.Main -i progress-openedge -ih localhost -idb ppoiss -iu pub -ip pub -ipn 13001 -e SIARD-2 -ef ppoiss.siard

ERROR Command '-i' not a valid command.
Database Preservation ToolkitDatabase Preservation Toolkit (version 2.4.0-BETA2)
More info: http://www.database-preservation.com


Same command with ...BETA.jar works perfectly

**Comment by hmiguim** [comment]
Hi, 

This new beta release (BETA2) we add the edit functionality, for differentiate a migration from an edition, we had to add a keyword (migrate or edit). So, in order to perform a migration you need to run the same command with the migrate keyword, like so:
jre1.8.0_201/bin/java "-Dfile.encoding=UTF-8" -cp "dbptk-app-2.4.0-BETA2.jar:openedge.jar" com.databasepreservation.Main **migrate** -i progress-openedge -ih localhost -idb ppoiss -iu pub -ip ****** -ipn 13001 -e SIARD-2 -ef ppoiss.siard

**Comment by Laurira** [comment]
Thanks,

Now the command works but there are still errors. It seems to have problem with max length or precision.

Error:
java.sql.sqlexception: [DataDirect][OpenEdge JDBC Driver][OpenEdge] Column to_message in table PUB.dok_adressaadid has value exceeding its max length or precision.
	at com.ddtek.jdbc.openedge.client.dde.ah(Unknown Source)
	at com.ddtek.jdbc.openedge.client.dde.ag(Unknown Source)
	at com.ddtek.jdbc.openedge.dde.a(Unknown Source)
	at com.ddtek.jdbc.openedgebase.ddcq.aa(Unknown Source)
	at com.ddtek.jdbc.openedgebase.dddm.next(Unknown Source)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.resultSetNext(JDBCImportModule.java:1641)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.resultSetNext(JDBCImportModule.java:1668)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.resultSetNext(JDBCImportModule.java:1664)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.migrateDatabaseTo(JDBCImportModule.java:1711)
	at com.databasepreservation.DatabaseMigration.migrate(DatabaseMigration.java:96)
	at com.databasepreservation.Main.runMigration(Main.java:241)
	at com.databasepreservation.Main.internalMain(Main.java:118)


I will send the full log to Luis.
