### ISSUE TITLE
NPE when migrating schema without tables

### ISSUE THREAD

**Issue by chalkos** [keeps/db-preservation-toolkit#369]
> I tried the same thing
> Database Sakila MySql (localhost) ->SIARD2 ->Postgresql -> SIARD2
> 
> The last conversion gives still an error. This -ede error is gone but it creates still an empty SIARD file and log says:
> 
```
2019-01-28 09:55:29,385 [main] ERROR (c.d.Main) Fatal error: Unexpected exception (null)
java.lang.NullPointerException: null
at com.databasepreservation.model.modules.filters.ObservableFilter.handleDataCloseSchema(ObservableFilter.java:143)
at com.databasepreservation.modules.jdbc.in.JDBCImportModule.migrateDatabaseTo(JDBCImportModule.java:1650)
at com.databasepreservation.DatabaseMigration.migrate(DatabaseMigration.java:79)
at com.databasepreservation.Main.run(Main.java:173)
at com.databasepreservation.Main.internalMain(Main.java:115)
at com.databasepreservation.Main.main(Main.java:89)
```

by @Laurira in #286

**Comment by Laurira** [comment]
WARN  Schema public was not exported because it does not contain tables.
      Completed database migration
      Database migration took 0m 8s to complete.
