### ISSUE TITLE
NPE error on loading LOBs outside the database

### ISSUE THREAD

**Issue by luis100** [keeps/db-preservation-toolkit#375]
Made first test with sakila database (mysql on windows)
```
I got java.lang.NullPointerException: null
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at sun.nio.fs.AbstractPath.resolve(Unknown Source)
```

This is how my database table with external lobs looks like
![error](https://user-images.githubusercontent.com/3479156/57123734-86258b80-6d8b-11e9-808e-ac1c7ab23aa1.JPG)

file path is `C:\Users\laurir\Desktop\DBPTK\SakilaPictureFolder\a13c4e637be4f4a33331ebbfe9c7956c.jpg`

Command that I executed
```
java "-Dfile.encoding=UTF-8" -jar .\dbptk-app-2.3.0-RC.jar -i mysql --import-hostname=localhost -idb sakila -iu root -ip parool -e siard-2 -ef sakila.siard -f external-lobs --filter1-reference-t
ype file-system --filter1-column-list .\sakilaListTablesWithExternalLobs
```

column list has one row in it
`sakila.customer{avatarFilePath;}`

**Did I do something wrong?**
At the moment the creation of siard fails when starting to convert the table customer.

_Originally posted by @Laurira in https://github.com/keeps/db-preservation-toolkit/issues/346#issuecomment-488977709_

**Comment by luis100** [comment]
Also see all possible reasons for failures, for example:
- [ ] Values are null
- [ ] Values are not valid paths
- [ ] Paths do not exist
- [ ] Paths exist but are not valid files (are directories, or broken symlinks)
- [ ] I/O errors getting the file content

**Comment by Laurira** [comment]
I see there are nice little debug messages in the log now
2019-05-08 10:03:03,629 [main] DEBUG (c.d.m.Reporter) something was ignored, message: - Information: `Cell customer.avatarFilePath.1` was ignored because reference to external LOB is null
But there are 599 of these messages. Two of these are not null.
So lob10 folder is still missing. Please test it before you release something.

![lob10StillMissing](https://user-images.githubusercontent.com/3479156/57356710-ddf03800-7179-11e9-978c-1355d3beffc7.JPG)

**Comment by luis100** [comment]
@tomasmferreira please look into previous comment and also fill up [my checklist](https://github.com/keeps/db-preservation-toolkit/issues/375#issuecomment-488984600).
