### ISSUE TITLE
dbptk 2.4.0-RC edit --set dbname: exception with MS Access

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#380]
Description: 

1. create a SIARD file from MS Access .mdb with dbptk-app-2.3.0.jar
2. deploy to PostgreSQL: I get na error "PUBLIC exists"
3.  manually rename default public to PUBLIC and deploy works
4. now I want to fix PUBLIC->public in the SIARD file
5. 
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/3289799/dbptk-app.log.txt)
java -Xmx1000m -Dfile.encoding=UTF-8 -jar ..\dbptk-app-2.4.0-RC.jar edit -if Izkaznice_IV_MNZ_only.siard --set dbname 'public'
      Edit SIARD metadata of Izkaznice_IV_MNZ_only.siard
      Importing SIARD version 2.1
      Changing dbname from 'PUBLIC' to ''public''
      Metadata for dbname successfully updated
Exception in thread "main" java.lang.IllegalArgumentException: Illegal character in opaque part at index 30: jar:file:/m:/Projekti/eARHsi/4 DBPTK/004_MNZ_varnostniki/Izkaznice_IV_MNZ_only.siard
        at java.net.URI.create(Unknown Source)
        at com.databasepreservation.modules.siard.out.update.MetadataUpdateStrategy.updateSIARDArchive(MetadataUpdateStrategy.java:93)
        at com.databasepreservation.modules.siard.out.metadata.SIARD21MetadataExportStrategy.updateMetadataXML(SIARD21MetadataExportStrategy.java:157)
        at com.databasepreservation.modules.siard.update.SIARDEditModule.updateMetadata(SIARDEditModule.java:163)
        at com.databasepreservation.SIARDEdition.edit(SIARDEdition.java:122)
        at com.databasepreservation.Main.runEdition(Main.java:189)
        at com.databasepreservation.Main.internalMain(Main.java:122)
        at com.databasepreservation.Main.main(Main.java:73)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 30: jar:file:/m:/Projekti/eARHsi/4 DBPTK/004_MNZ_varnostniki/Izkaznice_IV_MNZ_only.siard
        at java.net.URI$Parser.fail(Unknown Source)
6. Besides, what will be the name of the target SIARD file? "-ef" option was not accepted.

Attached the dbptk-app.log.txt

**Comment by hmiguim** [comment]
I found what it is, you have a space in the path to the SIARD file. "/Projekti/eARHsi/4 DBPTK/004_MNZ_varnostniki/Izkaznice_IV_MNZ_only.siard" the folder '4 DBPTK' is causing the illegal character error. I'll fix the bug and in the meantime please test the same SIARD file but with the path without spaces just to confirm the bug.

Regarding the point 6, there's none export option, the target SIARD is the import SIARD.

**Comment by BorisDomajnko** [comment]
Hi, now it is different:
m:\Projekti\eARHsi\4_DBPTK\004_MNZ_varnostniki>java -Xmx1000m -Dfile.encoding=UTF-8 -jar ..\dbptk-app-2.4.0-RC.jar edit -if Izkaznice_IV_MNZ_only.siard  --set dbname 'public'
      Edit SIARD metadata of Izkaznice_IV_MNZ_only.siard
      Importing SIARD version 2.1
      Changing dbname from 'PUBLIC' to ''public''
      Metadata for dbname successfully updated
Exception in thread "main" java.lang.UnsupportedOperationException
        at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:123)
        at java.nio.file.FileSystems.newFileSystem(Unknown Source)
        at com.databasepreservation.modules.siard.out.update.MetadataUpdateStrategy.updateSIARDArchive(MetadataUpdateStrategy.java:102)
        at com.databasepreservation.modules.siard.out.metadata.SIARD21MetadataExportStrategy.updateMetadataXML(SIARD21MetadataExportStrategy.java:157)
        at com.databasepreservation.modules.siard.update.SIARDEditModule.updateMetadata(SIARDEditModule.java:163)
        at com.databasepreservation.SIARDEdition.edit(SIARDEdition.java:122)
        at com.databasepreservation.Main.runEdition(Main.java:189)
        at com.databasepreservation.Main.internalMain(Main.java:122)
        at com.databasepreservation.Main.main(Main.java:73)
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/3290281/dbptk-app.log.txt)

**Comment by hmiguim** [comment]
Hi,

It appears that SIARD file generated by newer versions of DBPTK are given that error when editing the metadata. I'll look into it and come up with an answer.

Regarding the issue, I'll close it since its fixed on 967b643, and open a new one with the new error.
