### ISSUE TITLE
SIARD file generated by DBPTK-2.4.0-RC are giving error when editing the metadata.

### ISSUE THREAD

**Issue by hmiguim** [keeps/db-preservation-toolkit#381]
The error:

Exception in thread "main" java.lang.UnsupportedOperationException
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:123)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326)
	at com.databasepreservation.modules.siard.out.update.MetadataUpdateStrategy.updateSIARDArchive(MetadataUpdateStrategy.java:96)
	at com.databasepreservation.modules.siard.out.metadata.SIARD21MetadataExportStrategy.updateMetadataXML(SIARD21MetadataExportStrategy.java:157)
	at com.databasepreservation.modules.siard.update.SIARDEditModule.updateMetadata(SIARDEditModule.java:163)
	at com.databasepreservation.SIARDEdition.edit(SIARDEdition.java:122)
	at com.databasepreservation.Main.runEdition(Main.java:189)
	at com.databasepreservation.Main.internalMain(Main.java:122)
	at com.databasepreservation.Main.main(Main.java:73)

**Comment by hmiguim** [comment]
@BorisDomajnko

**Comment by hmiguim** [comment]
@BorisDomajnko the bug was found and updated, later today I'll release a new RC version where you can test the fix.

**Comment by hmiguim** [comment]
Closing the issue, resolved in 195386d. @BorisDomajnko generate a new SIARD archive and test the edit metadata feature.
