### ISSUE TITLE
DBPTK wrongly notices that a schema exists, but it does not

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-preservation-toolkit#392]
I just got a new siard file. It has has a schema "PUBLIC". In PostgreSQL there is a default schema "public". Deploying the siard file with DBPTK 2.4.0 I get an error. But if I manually create the PUBLIC schema, deployment works!

``
2019-09-07 22:44:39,710 [main] DEBUG (c.d.m.j.o.JDBCExportModule) Got a batch update exception while executing a batch statement
java.sql.BatchUpdateException: Batch entry 0 CREATE TABLE "PUBLIC"."dokumenty" ("DOKUMENTY" integer NULL, .....) was aborted: ERROR: schema "PUBLIC" does not exist
  Position: 14  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleCompletion(BatchResultHandler.java:163)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:471)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:793)
	at com.databasepreservation.modules.jdbc.out.JDBCExportModule.statementExecuteAndClearBatch(JDBCExportModule.java:872)
 . . .
2019-09-07 22:44:39,711 [main] DEBUG (c.d.m.j.o.JDBCExportModule) Next exception
org.postgresql.util.PSQLException: ERROR: schema "PUBLIC" does not exist
``

**Comment by hmiguim** [comment]
Hi Boris,

I'll look into the issue, if you provide the log would be helpful.

**Comment by hmiguim** [comment]
Appears that was used case insensitivity to check if the schema exists, so _public_ and _PUBLIC_ was the same thing, when it is not. Already solved, by changing the comparison to case sensitive.

Next version, 2.6.0 will have the fix.

If you want to test the change let me know, I can provide a SNAPSHOT version with the fix.
