### ISSUE TITLE
sybase - Fatal error - nullpointerException  - TDS Protocol error: Invalid packet type 0x42 after connection

### ISSUE THREAD

**Issue by Laurira** [keeps/db-preservation-toolkit#412]
Tried to create SIARD with DBPTK 2.6.3 from Sybase database (Windows 10)
(Side note: With dbptk GUI the connection test succeeded but it kept thinking...)

DBPTK error:
![image](https://user-images.githubusercontent.com/3479156/68373874-6745ee80-014c-11ea-82ea-9b16733c37e9.png)

## Parameters

**Import module:** sybase
- hostname = localhost
- database = mnt
- username = dba
- password = <filtered>
- port-number = 2638

**Export module:** siard-2
- version = V2_1
- file = C:\Users\laurir\Desktop\DBPTK\teeregister\teeregWith263.siard
- compress = false
- pretty-xml = false
- external-lobs = false
- external-lobs-per-folder = 1000
- external-lobs-folder-size = 0
- table-filter = null

Date: 2019-11-07

## Details

- No issues to report.

From the log:
2019-11-07 10:42:07,177 [main] INFO  (c.d.m.m.f.ProgressLoggerObserver) Initializing database
2019-11-07 10:42:07,192 [main] INFO  (c.d.m.s.o.o.SIARDExportDefault) Exporting SIARD version 2.1
2019-11-07 10:42:07,255 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Loading JDBC Driver net.sourceforge.jtds.jdbc.Driver
2019-11-07 10:42:07,267 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Getting connection
2019-11-07 10:42:07,657 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Connected
2019-11-07 10:42:07,661 [main] DEBUG (c.d.m.j.i.JDBCImportModule) driver version: 1.3.1
2019-11-07 10:42:07,674 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Closing connection to source database
2019-11-07 10:42:07,675 [main] ERROR (c.d.Main) Fatal error: Unexpected exception (null)
java.lang.NullPointerException: null
	at java.util.regex.Pattern.<init>(Unknown Source)
	at java.util.regex.Pattern.compile(Unknown Source)
	at java.util.regex.Pattern.matches(Unknown Source)
	at java.lang.String.matches(Unknown Source)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.isIgnoredImportedSchema(JDBCImportModule.java:437)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getSchemas(JDBCImportModule.java:456)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabaseStructure(JDBCImportModule.java:404)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.migrateDatabaseTo(JDBCImportModule.java:1948)
	at com.databasepreservation.DatabaseMigration.migrate(DatabaseMigration.java:102)
	at com.databasepreservation.Main.runMigration(Main.java:295)
	at com.databasepreservation.Main.internalMain(Main.java:122)
	at com.databasepreservation.Main.main(Main.java:76)
	Suppressed: java.sql.SQLException: TDS Protocol error: Invalid packet type 0x42
		at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2486)
		at net.sourceforge.jtds.jdbc.TdsCore.getNextRow(TdsCore.java:805)
		at net.sourceforge.jtds.jdbc.JtdsResultSet.next(JtdsResultSet.java:611)
		at net.sourceforge.jtds.jdbc.JtdsResultSet.close(JtdsResultSet.java:503)
		at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getSchemas(JDBCImportModule.java:462)
		... 6 common frames omitted
	Caused by: net.sourceforge.jtds.jdbc.ProtocolException: Invalid packet type 0x42
		at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2475)
		... 10 common frames omitted
2019-11-07 10:42:07,689 [main] INFO  (c.d.Main) Log files and migration reports were saved in 

The log:
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/3818640/dbptk-app.log.txt)

**Comment by hmiguim** [comment]
Close at 7e660f1
