### ISSUE TITLE
fatal error while importing from Oracle to SIARD - unsupported datatype - BFILE - cvc-pattern-valid - Value 'CHARACTER(0)' is not facet-valid

### ISSUE THREAD

**Issue by Laurira** [keeps/db-preservation-toolkit#413]
Tried to create siard-2 from Oracle. One table, 13 views.
Error occurs when all the tables and schemas are completed?
![image](https://user-images.githubusercontent.com/3479156/68661011-e66b6600-0542-11ea-8fd9-bc152b69ced4.png)

Log file is here:
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/3835441/dbptk-app.log.txt)

So I do not understand if the migration is complete or not...

**Comment by Laurira** [comment]
I tried with the newer version and seems like it finished the tables but still some error

2019-11-19 13:00:02,066 [main] INFO  (c.d.m.m.f.ProgressLoggerObserver) Progress: 368680 rows of table 'VIEW_MV_HLEHITISEKUJU' (100%)
2019-11-19 13:00:02,066 [main] INFO  (c.d.m.m.f.ProgressLoggerObserver) Completed table 'VIEW_MV_HLEHITISEKUJU' (4 of 4 tables completed)
2019-11-19 13:00:02,066 [main] INFO  (c.d.m.m.f.ProgressLoggerObserver) Completed schema 'EHR' (1 of 1 schemas completed)
2019-11-19 13:00:02,066 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Freeing resources
2019-11-19 13:00:03,534 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Closing connection to source database
2019-11-19 13:00:03,587 [main] ERROR (c.d.Main) Fatal error while converting the database (Error while Marshalling JAXB)
com.databasepreservation.model.exception.ModuleException: Error while Marshalling JAXB
	at com.databasepreservation.modules.siard.out.metadata.SIARD21MetadataExportStrategy.writeMetadataXML(SIARD21MetadataExportStrategy.java:203)
	at com.databasepreservation.modules.siard.out.output.SIARDExportDefault.finishDatabase(SIARDExportDefault.java:244)
	at com.databasepreservation.modules.externalLobs.ExternalLOBSFilter.finishDatabase(ExternalLOBSFilter.java:184)
	at com.databasepreservation.model.modules.filters.IdentityFilter.finishDatabase(IdentityFilter.java:107)
	at com.databasepreservation.model.modules.filters.ObservableFilter.finishDatabase(ObservableFilter.java:151)
	at com.databasepreservation.modules.jdbc.in.JDBCImportModule.migrateDatabaseTo(JDBCImportModule.java:2046)
	at com.databasepreservation.DatabaseMigration.migrate(DatabaseMigration.java:102)
	at com.databasepreservation.Main.runMigration(Main.java:295)
	at com.databasepreservation.Main.internalMain(Main.java:122)
	at com.databasepreservation.Main.main(Main.java:76)
Caused by: javax.xml.bind.MarshalException: null
	at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.write(MarshallerImpl.java:311)
	at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.marshal(MarshallerImpl.java:236)
	at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:95)
	at com.databasepreservation.modules.siard.out.metadata.SIARD21MetadataExportStrategy.writeMetadataXML(SIARD21MetadataExportStrategy.java:200)
	... 9 common frames omitted
Caused by: org.xml.sax.SAXParseException: cvc-pattern-valid: Value 'CHARACTER(0)' is not facet-valid with respect to pattern '(INTEGER|INT|SMALLINT|BIGINT)(\s+ARRAY(\s+\[[0-9]+\])?)?|(NUMERIC|DECIMAL|DEC)(\s*\(\s*[1-9]\d*\s*(,\s*\d+\s*)?\))?(\s+ARRAY(\s+\[[0-9]+\])?)?|REAL|DOUBLE PRECISION(\s+ARRAY(\s+\[[0-9]+\])?)?|FLOAT(\s*\(\s*[1-9]\d*\s*\))?(\s+ARRAY(\s+\[[0-9]+\])?)?|(CHARACTER|CHAR)(\s*\(\s*[1-9]\d*\s*\))?(\s+ARRAY(\s+\[[0-9]+\])?)?|(CHARACTER\s+VARYING|CHAR\s+VARYING|VARCHAR)(\s*\(\s*[1-9]\d*\s*\))(\s+ARRAY(\s+\[[0-9]+\])?)?|(CHARACTER\s+LARGE\s+OBJECT|CLOB)(\s*\(\s*[1-9]\d*(\s*(K|M|G))?\s*\))?(\s+ARRAY(\s+\[[0-9]+\])?)?|(NATIONAL\s+CHARACTER|NATIONAL\s+CHAR|NCHAR)(\s*\(\s*[1-9]\d*\s*\))?(\s+ARRAY(\s+\[[0-9]+\])?)?|(NATIONAL\s+CHARACTER\s+VARYING|NATIONAL\s+CHAR\s+VARYING|NCHAR VARYING)(\s*\(\s*[1-9]\d*\s*\))(\s+ARRAY(\s+\[[0-9]+\])?)?|(NATIONAL\s+CHARACTER\s+LARGE\s+OBJECT|NCHAR\s+LARGE\s+OBJECT|NCLOB)(\s*\(\s*[1-9]\d*(\s*(K|M|G))?\s*\))?(\s+ARRAY(\s+\[[0-9]+\])?)?|XML(\s+ARRAY(\s+\[[0-9]+\])?)?|BINARY(\s*\(\s*[1-9]\d*\s*\))?(\s+ARRAY(\s+\[[0-9]+\])?)?|(BINARY\s+VARYING|VARBINARY)(\s*\(\s*[1-9]\d*\s*\))(\s+ARRAY(\s+\[[0-9]+\])?)?|(BINARY\s+LARGE\s+OBJECT|BLOB)(\s*\(\s*[1-9]\d*(\s*(K|M|G))?\s*\))?(\s+ARRAY(\s+\[[0-9]+\])?)?|DATE(\s+ARRAY(\s+\[[0-9]+\])?)?|(TIME|TIME\s+WITH\s+TIME\s+ZONE)(\s*\(\s*[1-9]\d*\s*\))?(\s+ARRAY(\s+\[[0-9]+\])?)?|(TIMESTAMP|TIMESTAMP\s+WITH\s+TIME\s+ZONE)(\s*\(\s*(0|([1-9]\d*))\s*\))?(\s+ARRAY(\s+\[[0-9]+\])?)?|INTERVAL\s+(((YEAR|MONTH|DAY|HOUR|MINUTE)(\s*\(\s*[1-9]\d*\s*\))?(\s+TO\s+(MONTH|DAY|HOUR|MINUTE|SECOND)(\s*\(\s*[1-9]\d*\s*\))?)?)|(SECOND(\s*\(\s*[1-9]\d*\s*(,\s*\d+\s*)?\))?))(\s+ARRAY(\s+\[[0-9]+\])?)?|BOOLEAN(\s+ARRAY(\s+\[[0-9]+\])?)?' for type 'predefinedTypeType'.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:453)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3231)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.elementLocallyValidType(XMLSchemaValidator.java:3146)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.processElementContent(XMLSchemaValidator.java:3056)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleEndElement(XMLSchemaValidator.java:2135)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.endElement(XMLSchemaValidator.java:854)
	at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorHandlerImpl.endElement(ValidatorHandlerImpl.java:582)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)

**Comment by Laurira** [comment]
Here is the log file as well 
[dbptk-app.log.txt](https://github.com/keeps/db-preservation-toolkit/files/3862657/dbptk-app.log.txt)

**Comment by Laurira** [comment]
It is a blocker issue as the metadata.xml is empty...

**Comment by hmiguim** [comment]
Close at 02d425c

**Comment by Laurira** [comment]
Seem like the BFILE still causes issues, got fatal error:
From the log:
![image](https://user-images.githubusercontent.com/3479156/69612772-0f0e5800-1039-11ea-8575-1beeb0e378d7.png)
From the log:
![image](https://user-images.githubusercontent.com/3479156/69612817-251c1880-1039-11ea-801d-ddc24eb6232c.png)
